# Generated by Django 2.1.7 on 2019-03-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190316_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_time',
            new_name='date',
        ),
    ]
